apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: flask-todo-cluster
  region: eu-west-2

addons:
  - name: aws-ebs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
