name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  IMAGE_TAG: ${{ github.sha }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build-and-deploy:
    name: Build, Push to ECR & Deploy to EKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .

    - name: Push Docker image to ECR
      run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Install kubectl
      uses: kubernetes-sigs/setup-kubectl@v1
      with:
        version: 'v1.30'


    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name ${{ secrets.CLUSTER_NAME }}

    - name: Deploy to EKS
      run: |
        kubectl set image deployment/flask-app flask-app=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Wait for rollout
      run: kubectl rollout status deployment/flask-app
