name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/app" >> $GITHUB_ENV

      - name: Run tests
        run: pytest
